import Head from 'next/head'
import Image from 'next/image'
import { Provider, createClient } from 'wagmi'
import { useAccount, useConnect, useDisconnect, useEnsName } from 'wagmi'
import { MetaMaskConnector } from 'wagmi/connectors/metaMask'
import styles from '../styles/Home.module.css'

const client = createClient()
const connector = new MetaMaskConnector()

function Profile() {
  const { data: account } = useAccount()
  const { data: ensName } = useEnsName({ address: account?.address })
  const { connect } = useConnect({ connector })
  const { disconnect } = useDisconnect()

  if (account) {
    return (
      <div>
        <div>
          {ensName ? `${ensName} (${account.address})` : account.address}
        </div>
        <div>Connected to {account.connector.name}</div>
        <button onClick={disconnect}>Disconnect</button>
      </div>
    )
  }
  return <button onClick={() => connect()}>Connect Wallet</button>
}

export default function Home() {
  return (
    <Provider client={client}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Ethereum + React</h1>

          <Profile />
        </main>
      </div>
    </Provider>
  )
}
